INSERT INTO reviews
(product_id, user_id, rating, title, comment, is_verified_purchase, helpful_count)
VALUES
(1, 1, 5, 'Excellent Product', 'Would definitely buy again.', TRUE, 8),
(8, 2, 5, 'Excellent Product', 'Excellent quality and performance.', TRUE, 60),
(15, 3, 1, 'Not Recommended', 'Would not recommend.', TRUE, 93),
(22, 4, 3, 'Good Overall', 'Average product.', TRUE, 82),
(29, 5, 3, 'Good Overall', 'Nothing exceptional but usable.', TRUE, 91),
(36, 6, 3, 'Average Quality', 'Average product.', TRUE, 44),
(43, 7, 5, 'Highly Recommended', 'Excellent quality and performance.', TRUE, 45),
(50, 8, 2, 'Could Be Better', 'Expected better quality.', TRUE, 63),
(57, 9, 3, 'Meets Expectations', 'It''s okay for the price.', TRUE, 98),
(64, 10, 5, 'Highly Recommended', 'Fantastic product for the price.', TRUE, 94),
(71, 11, 5, 'Amazing Quality', 'Excellent quality and performance.', TRUE, 50),
(78, 12, 5, 'Amazing Quality', 'Fantastic product for the price.', TRUE, 21),
(85, 13, 4, 'Good Packaging', 'Works well and is worth buying.', TRUE, 70),
(92, 14, 3, 'Good Overall', 'Nothing exceptional but usable.', TRUE, 104),
(99, 15, 5, 'Amazing Quality', 'Would definitely buy again.', TRUE, 35),
(6, 16, 4, 'Fast Delivery', 'Works well and is worth buying.', TRUE, 87),
(13, 17, 5, 'Excellent Product', 'Exceeded my expectations.', TRUE, 19),
(20, 18, 4, 'Nice Design', 'Good quality with minor issues.', TRUE, 19),
(27, 19, 3, 'Average Quality', 'Average product.', TRUE, 29),
(34, 20, 3, 'Decent Product', 'Average product.', TRUE, 106),
(41, 21, 4, 'Worth the Money', 'Works well and is worth buying.', TRUE, 36),
(48, 22, 5, 'Loved It', 'Would definitely buy again.', TRUE, 53),
(55, 23, 4, 'Very Good', 'Satisfied with the purchase.', TRUE, 78),
(62, 24, 4, 'Very Good', 'Good quality with minor issues.', TRUE, 16),
(69, 25, 5, 'Excellent Product', 'Fantastic product for the price.', TRUE, 83),
(76, 26, 4, 'Very Good', 'Satisfied with the purchase.', TRUE, 115),
(83, 27, 5, 'Amazing Quality', 'Fantastic product for the price.', TRUE, 50),
(90, 28, 5, 'Amazing Quality', 'Fantastic product for the price.', TRUE, 13),
(97, 29, 5, 'Highly Recommended', 'Excellent quality and performance.', TRUE, 7),
(4, 30, 2, 'Not as Expected', 'Expected better quality.', TRUE, 26),
(11, 1, 3, 'Meets Expectations', 'Nothing exceptional but usable.', TRUE, 14),
(18, 2, 3, 'Average Quality', 'It''s okay for the price.', TRUE, 6),
(25, 3, 4, 'Nice Design', 'Good quality with minor issues.', TRUE, 72),
(32, 4, 4, 'Good Packaging', 'Good quality with minor issues.', TRUE, 12),
(39, 5, 2, 'Could Be Better', 'Expected better quality.', TRUE, 3),
(46, 6, 1, 'Disappointed', 'Very disappointing experience.', TRUE, 78),
(53, 7, 3, 'Meets Expectations', 'Average product.', TRUE, 81),
(60, 8, 2, 'Not as Expected', 'Has a few noticeable issues.', TRUE, 77),
(67, 9, 4, 'Worth the Money', 'Satisfied with the purchase.', TRUE, 15),
(74, 10, 5, 'Amazing Quality', 'Fantastic product for the price.', TRUE, 59),
(81, 11, 5, 'Excellent Product', 'Exceeded my expectations.', TRUE, 39),
(88, 12, 2, 'Average Experience', 'Has a few noticeable issues.', TRUE, 13),
(95, 13, 5, 'Value for Money', 'Fantastic product for the price.', TRUE, 94),
(2, 14, 4, 'Nice Design', 'Good quality with minor issues.', TRUE, 106),
(9, 15, 5, 'Highly Recommended', 'Would definitely buy again.', TRUE, 2),
(16, 16, 5, 'Loved It', 'Excellent quality and performance.', TRUE, 18),
(23, 17, 4, 'Very Good', 'Satisfied with the purchase.', TRUE, 97),
(30, 18, 5, 'Excellent Product', 'Would definitely buy again.', TRUE, 82),
(37, 19, 4, 'Good Packaging', 'Works well and is worth buying.', TRUE, 66),
(44, 20, 2, 'Could Be Better', 'Not fully satisfied.', TRUE, 45),
(51, 21, 4, 'Very Good', 'Satisfied with the purchase.', TRUE, 69),
(58, 22, 4, 'Nice Design', 'Good quality with minor issues.', TRUE, 81),
(65, 23, 4, 'Nice Design', 'Works well and is worth buying.', TRUE, 103),
(72, 24, 5, 'Amazing Quality', 'Exceeded my expectations.', TRUE, 104),
(79, 25, 2, 'Average Experience', 'Has a few noticeable issues.', TRUE, 25),
(86, 26, 4, 'Worth the Money', 'Works well and is worth buying.', TRUE, 45),
(93, 27, 4, 'Good Packaging', 'Satisfied with the purchase.', TRUE, 101),
(100, 28, 3, 'Decent Product', 'Nothing exceptional but usable.', TRUE, 33),
(7, 29, 3, 'Meets Expectations', 'Average product.', TRUE, 77),
(14, 30, 3, 'Meets Expectations', 'Average product.', TRUE, 103),
(21, 1, 4, 'Nice Design', 'Works well and is worth buying.', TRUE, 10),
(28, 2, 4, 'Fast Delivery', 'Works well and is worth buying.', TRUE, 29),
(35, 3, 4, 'Nice Design', 'Satisfied with the purchase.', TRUE, 43),
(42, 4, 4, 'Very Good', 'Works well and is worth buying.', TRUE, 79),
(49, 5, 3, 'Meets Expectations', 'Nothing exceptional but usable.', TRUE, 61),
(56, 6, 5, 'Excellent Product', 'Fantastic product for the price.', TRUE, 10),
(63, 7, 1, 'Not Recommended', 'Very disappointing experience.', TRUE, 100),
(70, 8, 4, 'Nice Design', 'Satisfied with the purchase.', TRUE, 61),
(77, 9, 5, 'Value for Money', 'Excellent quality and performance.', TRUE, 101),
(84, 10, 5, 'Amazing Quality', 'Fantastic product for the price.', TRUE, 102),
(91, 11, 2, 'Average Experience', 'Expected better quality.', TRUE, 51),
(98, 12, 1, 'Poor Battery Life', 'Very disappointing experience.', TRUE, 92),
(5, 13, 1, 'Poor Battery Life', 'Very disappointing experience.', TRUE, 16),
(12, 14, 3, 'Good Overall', 'Nothing exceptional but usable.', TRUE, 75),
(19, 15, 5, 'Loved It', 'Fantastic product for the price.', TRUE, 18),
(26, 16, 5, 'Value for Money', 'Exceeded my expectations.', TRUE, 84),
(33, 17, 3, 'Decent Product', 'It''s okay for the price.', TRUE, 70),
(40, 18, 2, 'Average Experience', 'Not fully satisfied.', TRUE, 1),
(47, 19, 4, 'Very Good', 'Good quality with minor issues.', TRUE, 13),
(54, 20, 3, 'Decent Product', 'Average product.', TRUE, 119),
(61, 21, 2, 'Could Be Better', 'Expected better quality.', FALSE, 111),
(68, 22, 5, 'Value for Money', 'Exceeded my expectations.', FALSE, 3),
(75, 23, 5, 'Loved It', 'Exceeded my expectations.', FALSE, 37),
(82, 24, 4, 'Very Good', 'Satisfied with the purchase.', FALSE, 97),
(89, 25, 4, 'Very Good', 'Satisfied with the purchase.', FALSE, 33),
(96, 26, 5, 'Highly Recommended', 'Excellent quality and performance.', FALSE, 106),
(3, 27, 5, 'Value for Money', 'Fantastic product for the price.', FALSE, 116),
(10, 28, 5, 'Loved It', 'Fantastic product for the price.', FALSE, 84),
(17, 29, 4, 'Very Good', 'Works well and is worth buying.', FALSE, 105),
(24, 30, 5, 'Highly Recommended', 'Excellent quality and performance.', FALSE, 68),
(31, 1, 3, 'Good Overall', 'It''s okay for the price.', FALSE, 111),
(38, 2, 4, 'Worth the Money', 'Works well and is worth buying.', FALSE, 77),
(45, 3, 5, 'Highly Recommended', 'Fantastic product for the price.', FALSE, 22),
(52, 4, 3, 'Average Quality', 'Nothing exceptional but usable.', FALSE, 79),
(59, 5, 5, 'Value for Money', 'Fantastic product for the price.', FALSE, 7),
(66, 6, 5, 'Excellent Product', 'Excellent quality and performance.', FALSE, 100),
(73, 7, 3, 'Decent Product', 'Average product.', FALSE, 31),
(80, 8, 4, 'Worth the Money', 'Good quality with minor issues.', FALSE, 5),
(87, 9, 5, 'Loved It', 'Excellent quality and performance.', FALSE, 57),
(94, 10, 4, 'Worth the Money', 'Satisfied with the purchase.', FALSE, 97);